"""empty message

Revision ID: 0018360cc206
Revises: b9124ae4a981
Create Date: 2018-01-21 17:20:28.965729

"""

# revision identifiers, used by Alembic.
revision = '0018360cc206'
down_revision = 'b9124ae4a981'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('office_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'office_name')
    # ### end Alembic commands ###
