"""empty message

Revision ID: 526b3c4b6aec
Revises: a62bf7a8f7d1
Create Date: 2018-01-16 00:10:01.804660

"""

# revision identifiers, used by Alembic.
revision = '526b3c4b6aec'
down_revision = 'a62bf7a8f7d1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'first_keyword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('first_keyword', mysql.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
