"""empty message

Revision ID: 836510b9f5c1
Revises: 0018360cc206
Create Date: 2018-01-21 18:18:17.955631

"""

# revision identifiers, used by Alembic.
revision = '836510b9f5c1'
down_revision = '0018360cc206'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'image')
    # ### end Alembic commands ###
